In [1]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [0]:
matriz = tf.constant([[1, 2], [3, 4]], name='matriz')
matriz2 = tf.constant([[-1, 3], [4, 2]], name='matriz2')

In [0]:
mult = tf.matmul(matriz, matriz2)

In [4]:
with tf.Session() as sess:
  print(sess.run(matriz))
  print('\n')
  print(sess.run(matriz2))
  print('\n')
  print(sess.run(mult))

[[1 2]
 [3 4]]


[[-1  3]
 [ 4  2]]


[[ 7  7]
 [13 17]]


In [0]:
mult2 = tf.matmul(matriz2, matriz)

In [10]:
with tf.Session() as sess:
  print(sess.run(mult2))

[[ 8 10]
 [10 16]]


In [0]:
matriz3 = tf.constant([[2, 3], [0, 1], [-1, 4]], name='matriz3')
matriz4 = tf.constant([[1, 2, 3], [-2, 0, 4]], name='matriz4')
mult3 = tf.matmul(matriz3, matriz4)

In [18]:
with tf.Session() as sess:
  print(sess.run(matriz3))
  print('\n')
  print(sess.run(matriz4))
  print('\n')
  print(sess.run(mult3))


[[ 2  3]
 [ 0  1]
 [-1  4]]


[[ 1  2  3]
 [-2  0  4]]


[[-4  4 18]
 [-2  0  4]
 [-9 -2 13]]
