In [1]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [0]:
placeholder = tf.placeholder('float', None)

In [0]:
operation = placeholder + 2

In [8]:
with tf.Session() as sess:
  #sess.run(operation)
  result = sess.run(operation, feed_dict={placeholder: [1, 2, 3]})
  print(result)


[3. 4. 5.]


In [0]:
placeholder2 = tf.placeholder('float', [None, 5])
operation2 = placeholder2 * 5

In [12]:
with tf.Session() as sess:
  data = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
  result = sess.run(operation2, feed_dict={placeholder2 :data}) 
  print(result)

[[ 5. 10. 15. 20. 25.]
 [30. 35. 40. 45. 50.]]
