In [1]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [0]:
val = tf.constant([9, 8, 7], name = 'val')
val1 = tf.constant([1, 2, 3], name = 'val1')

In [0]:
soma = val + val1

In [4]:
type(val)

tensorflow.python.framework.ops.Tensor

In [5]:
print(val)

Tensor("val:0", shape=(3,), dtype=int32)


In [6]:
with tf.Session() as sess:
  print(sess.run(soma))


[10 10 10]


In [0]:
matriz = tf.constant([[1, 2, 3], [4, 5, 6]], name = 'matriz')

In [8]:
type(matriz)

tensorflow.python.framework.ops.Tensor

In [9]:
print(matriz)

Tensor("matriz:0", shape=(2, 3), dtype=int32)


In [10]:
matriz.shape

TensorShape([Dimension(2), Dimension(3)])

In [0]:
matriz2 = tf.constant([[1, 2, 3], [4, 5, 6]], name = 'matriz2')

In [0]:
soma1 = tf.add(matriz, matriz2)

In [13]:
with tf.Session() as sess:
  print(sess.run(matriz))
  print('/n')
  print(sess.run(matriz2))
  print('/n')
  print(sess.run(soma1))

[[1 2 3]
 [4 5 6]]
/n
[[1 2 3]
 [4 5 6]]
/n
[[ 2  4  6]
 [ 8 10 12]]


In [19]:
matriz2 = tf.constant([[1, 2, 3], [4, 5, 6,]], name='matriz2')
matriz3 = tf.constant([[1], [2]], name='matriz3')
soma2 = tf.add(matriz2, matriz3)
print(soma2)

Tensor("Add_3:0", shape=(2, 3), dtype=int32)


In [21]:
with tf.Session() as sess:
  print(sess.run(matriz2))
  print('/n')
  print(sess.run(matriz3))
  print('/n')
  print(sess.run(soma2))


[[1 2 3]
 [4 5 6]]
/n
[[1]
 [2]]
/n
[[2 3 4]
 [6 7 8]]
