In [0]:
import pandas as pd
import tensorflow as tf
import tensorflow.compat.v1 as tf
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
tf.disable_v2_behavior()

In [2]:
base = pd.read_csv('/content/drive/My Drive/TensorFlow_1.x_guide/linear_regression/CSV/house_prices.csv')
base.head()

id             date     price  ...     long  sqft_living15  sqft_lot15
0  7129300520  20141013T000000  221900.0  ... -122.257           1340        5650
1  6414100192  20141209T000000  538000.0  ... -122.319           1690        7639
2  5631500400  20150225T000000  180000.0  ... -122.233           2720        8062
3  2487200875  20141209T000000  604000.0  ... -122.393           1360        5000
4  1954400510  20150218T000000  510000.0  ... -122.045           1800        7503

[5 rows x 21 columns]

In [0]:
X = base.iloc[:, 5:6].values
y = base.iloc[:, 2:3].values

In [4]:
X

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]])

In [5]:
y

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [402101.],
       [400000.],
       [325000.]])

In [0]:
scaler_X = StandardScaler()
scaler_y = StandardScaler()

In [0]:
X = scaler_X.fit_transform(X)
y = scaler_y.fit_transform(y)

In [8]:
X

array([[-0.97983502],
       [ 0.53363434],
       [-1.42625404],
       ...,
       [-1.15404732],
       [-0.52252773],
       [-1.15404732]])

In [9]:
y

array([[-0.86671733],
       [-0.00568792],
       [-0.98084935],
       ...,
       [-0.37586519],
       [-0.38158814],
       [-0.58588173]])

In [10]:
columns = [tf.feature_column.numeric_column('x', shape=1)]
columns

[NumericColumn(key='x', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [11]:
regressor = tf.estimator.LinearRegressor(feature_columns=columns)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpo1o8up79', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [13]:
X_train.shape

(15129, 1)

In [14]:
y_train.shape

(15129, 1)

In [15]:
X_test.shape

(6484, 1)

In [16]:
y_test.shape

(6484, 1)

In [0]:
function_train = tf.estimator.inputs.numpy_input_fn({'x': X_train}, y_train, batch_size=32, num_epochs= None, shuffle=True)

In [0]:
function_test = tf.estimator.inputs.numpy_input_fn({'x': X_test}, y_test, batch_size=32, num_epochs=1000, shuffle=False)

In [0]:
regressor.train(input_fn = function_train, steps = 10000)

In [23]:
metrics_train = regressor.evaluate(input_fn=function_train, steps=1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-05-18T22:25:24Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpo1o8up79/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [100/1000]
INFO:tensorflow:Evaluation [200/1000]
INFO:tensorflow:Evaluation [300/1000]
INFO:tensorflow:Evaluation [400/1000]
INFO:tensorflow:Evaluation [500/1000]
INFO:tensorflow:Evaluation [600/1000]
INFO:tensorflow:Evaluation [700/1000]
INFO:tensorflow:Evaluation [800/1000]
INFO:tensorflow:Evaluation [900/1000]
INFO:tensorflow:Evaluation [1000/1000]
INFO:tensorflow:Inference Time : 1.39291s
INFO:tensorflow:Finished evaluation at 2020-05-18-22:25:26
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.4851009, global_step = 10000, label/mean = -0.005687093, loss = 15.523229, prediction/mean = -0.0039180266
INFO:tensorflo

In [24]:
metric_test = regressor.evaluate(input_fn=function_test, steps=1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-05-18T22:26:32Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpo1o8up79/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [100/1000]
INFO:tensorflow:Evaluation [200/1000]
INFO:tensorflow:Evaluation [300/1000]
INFO:tensorflow:Evaluation [400/1000]
INFO:tensorflow:Evaluation [500/1000]
INFO:tensorflow:Evaluation [600/1000]
INFO:tensorflow:Evaluation [700/1000]
INFO:tensorflow:Evaluation [800/1000]
INFO:tensorflow:Evaluation [900/1000]
INFO:tensorflow:Evaluation [1000/1000]
INFO:tensorflow:Inference Time : 1.77932s
INFO:tensorflow:Finished evaluation at 2020-05-18-22:26:34
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.56610143, global_step = 10000, label/mean = 0.014971826, loss = 18.115246, prediction/mean = 0.004975827
INFO:tensorflow:

In [25]:
metrics_train

{'average_loss': 0.4851009,
 'global_step': 10000,
 'label/mean': -0.005687093,
 'loss': 15.523229,
 'prediction/mean': -0.0039180266}

In [26]:
metric_test

{'average_loss': 0.56610143,
 'global_step': 10000,
 'label/mean': 0.014971826,
 'loss': 18.115246,
 'prediction/mean': 0.004975827}

In [0]:
new_home = np.array([[800], [900], [1000]])

In [29]:
new_home

array([[ 800],
       [ 900],
       [1000]])

In [0]:
new_home = scaler_X.transform(new_home)

In [0]:
function_prevision = tf.estimator.inputs.numpy_input_fn({'x': new_home}, shuffle=False)

In [0]:
prevision = regressor.predict(input_fn=function_prevision)

In [35]:
list(prevision)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpo1o8up79/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([-0.9801061], dtype=float32)},
 {'predictions': array([-0.9036672], dtype=float32)},
 {'predictions': array([-0.82722825], dtype=float32)}]

In [37]:
for p in regressor.predict(input_fn=function_prevision):
  print(scaler_y.inverse_transform(p['predictions']))


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpo1o8up79/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
[180272.86]
[208335.02]
[236397.17]
