In [0]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
import numpy as np
tf.disable_v2_behavior()

In [0]:
X = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])

In [0]:
y = np.array([[0.0], [1.0], [1.0], [1.0]])

In [32]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [33]:
y

array([[0.],
       [1.],
       [1.],
       [1.]])

In [0]:
weights = tf.Variable(tf.zeros([2, 1], dtype=tf.float64))
init = tf.global_variables_initializer()

In [0]:
def step(x):
  return tf.cast(tf.to_float(tf.math.greater_equal(x,1)), tf.float64)

In [0]:
output_layer = tf.matmul(X, weights)

In [0]:
output_layer_activation = step(output_layer)

In [0]:
error = tf.subtract(y, output_layer_activation)

In [0]:
delta = tf.matmul(X, error, transpose_a=True)

In [0]:
train = tf.assign(weights, tf.add(weights, tf.multiply(delta, 0.1)))

In [41]:
with tf.Session() as sess:
  sess.run(init)
  epochs = 0
  for i in range(15):
    epochs += 1
    total_error, _ = sess.run([error, train])
    sum_error = tf.reduce_sum(total_error)
    print('Epochs: ', epochs, 'Error: ', sess.run(sum_error))
    if sum_error.eval() == 0.0:
      break
  final_weights = sess.run(weights)

Epochs:  1 Error:  3.0
Epochs:  2 Error:  3.0
Epochs:  3 Error:  3.0
Epochs:  4 Error:  2.0
Epochs:  5 Error:  2.0
Epochs:  6 Error:  2.0
Epochs:  7 Error:  2.0
Epochs:  8 Error:  0.0


In [42]:
final_weights

array([[1.],
       [1.]])

In [0]:
output_layer_test = tf.matmul(X, final_weights)
output_layer_ativation_test = step(output_layer_test)

In [44]:
with tf.Session() as sess:
  sess.run(init)
  print(sess.run(output_layer_ativation_test))

[[0.]
 [1.]
 [1.]
 [1.]]
